#!/bin/bash

# Get the current script directory
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

if [ $1 == "plugin" ]; then
  git submodule add -f http://github.com/$2/$3.git .vim/bundle/$3
else
  echo "Linking dotfiles..."
  for f in .*; do
    if [ $f != "." ] && [ $f != ".." ] && [ $f != ".git" ] && [ $f != ".gitmodules" ] && [ $f != ".gitignore" ] && [ $f != ".gitconfig" ]; then
      if [ -L ~/$f ]; then
        rm ~/$f
        ln -s $DIR/$f ~/$f
        echo "  Relinked $f"
      else
        ln -s $DIR/$f ~/$f
        echo "  Linked $f"
      fi
    fi
  done

#  echo "Initializing submodules..."
#  git submodule init --quiet
#  echo "Updating submodules..."
#  git submodule update --quiet
#  echo "Pulling submodules..."
#  git submodule foreach git pull origin master --quiet
fi
